function cCorr2(Obj, channel, ccFile)
% function cCorr2(Obj, channel, ccFile)
%
% Applied correction for chromatic aberrations on Obj which is
% either an image or an array of dots.
%
% Treated as dots if size(Obj, 2)==3 
%  and as an image if size(Obj,2)>3
%
% ccFile is a .mat file generated by cCorrM2




