% Extract the help from a few of the functions
% To be used before the documentation is compiled

functions = {'DOTTER', ...
    'nd2tif', ...
    'A_cells', ...
    'df_readTif', ...
    'write_tif_volume', ...
    'volume_slide', ...
    'dotter_slide', ...
    'dotterStartup', ...
    'piccs', ...
    'setUserDotsDNA', ...
    'dotFitting', ...
    'dotThreshold',...
    'dotCandidates', ...
    'df_getConfig', ...
    'df_setConfig', ...
    'cCorrMeasure', ...
    'df_fwhm', ...
    'NEditor', ...
    };

functions = sort(functions);

docdir = [getenv('DOTTER_PATH') 'dotter' filesep() 'documentation' filesep() 'matHelp'];

disp(['Extracting function help to ' docdir]);

if exist(docdir, 'dir') == 0
    mkdir(docdir);
end

indexFilename = [docdir filesep() 'index.tex'];
indexFile = fopen(indexFilename, 'w');


for kk = 1:numel(functions)    
    fprintf('%3d : %s\n', kk, functions{kk});
    fprintf(indexFile, '\\subsection{%s}', [strrep(functions{kk}, '_', '\_') '.m']);
    fprintf(indexFile, '\\verbatiminput{%s}\n', ['matHelp' filesep() functions{kk} '.txt']);
    s = help(functions{kk}); % help string
    filename = [docdir filesep() functions{kk} '.txt'];
    f = fopen(filename, 'w');
    fprintf(f, s);
    fclose(f);
end

fclose(indexFile);    
